[project]
name = "browser-task"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.20.0",
    "fastapi>=0.115.6",
    "uvicorn>=0.34.0",
]
